Repository auth0/auth0-java-mvc-common, pull requests merged in 2022-04, with the labels that each got.

#106 Update OkHttp version
  build.gradle
Labels: CH: Security

#107 Update auth0-java dependency
  build.gradle
Labels: CH: Security, review:tiny

#108 Release 1.9.2
  CHANGELOG.md
  README.md
Labels: review:tiny
